### ISSUE TITLE
Pass a Logger function into API

### ISSUE THREAD

**Issue by MSabherwal** [derekdowling/jsh-api#3]
Can New take a logger function as well? I'd feel more comfortable if logging was explicit rather than implicit. Something like:

``` go
func New(prefix string,logger *log.Logger) *API {

    if len(prefix) > 0 && !strings.HasPrefix(prefix, "/") {
        prefix = fmt.Sprintf("/%s", prefix)
    }

    return &API{
        Mux:       goji.NewMux(),
        prefix:    prefix,
        Resources: map[string]*Resource{},
        Logger:    logger,
    }
}
```

also, I was considering adding the route the error occured within into the log message, so a standard log return would look like:

``` go
log.Print(fmt.Sprintf("Error:%v: Some high level description: %v",c.GetMatch.RawPattern.(string),err))
```

(built that from looking at goji docs, so ymmv). Thoughts?

**Comment by derekdowling** [comment]
I guess it's reasonable to think about logging out of the box. Closed by #https://github.com/derekdowling/jsh-api/commit/c222dec8d7ee0724b390d8c26c24456e40a4561b#diff-651a84f8ad6a38c1f7ccdf63f2692410R22
